apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins
  namespace: elk
  labels:
    type: local
spec:
  storageClassName: jenkins-data
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/ubuntu/data/jenkins"
  claimRef:
    name: jk-pv-claim
    namespace: elk
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jk-pv-claim
  namespace: elk
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: jenkins-data
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: elk
  labels:
    app: jenkins
spec:
  selector:
    matchLabels:
      app: jenkins
  replicas: 
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      serviceAccountName: jenkins-admin
      containers:
      - name: jenkins
        image: jenkins/jenkins:lts
        securityContext:                     
          runAsUser: 0
          privileged: true
        ports:
        - name: http
          containerPort: 8080
        - name: jnlp
          containerPort: 50000
        resources:
          limits:
            memory: 1Gi
            cpu: "600m"
          requests:
            memory: 512Mi
            cpu: "200m"
        env:
        - name: LIMITS_MEMORY
          valueFrom:
            resourceFieldRef:
              resource: limits.memory
              divisor: Mi
        - name: "JAVA_OPTS"  #设置变量，指定时区和 jenkins slave 执行者设置
          value: "
                   -Xmx512m -Xms512m
                   -XshowSettings:vm
                   -Dhudson.slaves.NodeProvisioner.initialDelay=0
                   -Dhudson.slaves.NodeProvisioner.MARGIN=50
                   -Dhudson.slaves.NodeProvisioner.MARGIN0=0.85
                   -Duser.timezone=Asia/Shanghai
                 "    
        - name: "JENKINS_OPTS"
          value: "--prefix=/jenkins"         #设置路径前缀加上 Jenkins
        volumeMounts:                        #设置要挂在的目录
        - name: data
          mountPath: /var/jenkins_home
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: jk-pv-claim      #设置PVC
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: elk
  labels:
    app: jenkins
spec:
  ports:
  - name: http
    port: 8080     #服务端口
    targetPort: http
    #nodePort:   #NodePort方式暴露 Jenkins 端口
  - name: jnlp
    port: 50000    #代理端口
    targetPort: jnlp 
    #nodePort: 
  selector:
    app: jenkins
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: jenkins
  namespace: elk
spec:
  entryPoints:
    - web
  routes:
    - match: PathPrefix(`/jenkins`)
      kind: Rule
      services:
        - name: jenkins
          namespace: elk
          port: 8080
