apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: kibana
  name: kibana
  namespace: elk
spec:
  selector:
    matchLabels:
      k8s-app: kibana
  template:
    metadata:
      labels:
        k8s-app: kibana
    spec:
      containers:
        - image: kibana:8.15.2
          imagePullPolicy: IfNotPresent
          name: kibana
          env:
            - name: ELASTICSEARCH_HOSTS
              value: http://elasticsearch:9200
            - name: ELASTICSEARCH_USERNAME
              valueFrom:
                secretKeyRef:
                  name: popersecret
                  key: kibana-username
            - name: ELASTICSEARCH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: popersecret
                  key: kibana-password
          ports:
            - containerPort: 5601
              name: http
              protocol: TCP
          volumeMounts:
            - mountPath: /usr/share/kibana/config/kibana.yml
              name: kibana
              subPath: kibana
      volumes:
        - configMap:
            defaultMode: 429
            name: kibana
          name: kibana
---
apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: elk
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: http
  selector:
    k8s-app: kibana
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: kibana
  namespace: elk
spec:
  entryPoints:
    - web
  routes:
    - match: not PathPrefix(\`/notls\`)
      kind: Rule
      services:
        - name: whoami
          port: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-http
  namespace: elk
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kibana
                port:
                  number: 80

