apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: logstash
  name: logstash
  namespace: elk
spec:
  selector:
    matchLabels:
      k8s-app: logstash
  template:
    metadata:
      labels:
        k8s-app: logstash
    spec:
      containers:
        - name: logstash
          image: logstash:8.15.2
          env:
            - name: ELASTICSEARCH_HOSTS
              value: http://elasticsearch:9200
            - name: LOGSTASH_USERNAME
              valueFrom:
                secretKeyRef:
                  name: popersecret
                  key: logstash-username
            - name: LOGSTASH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: popersecret
                  key: logstash-password
          ports:
            - containerPort: 8088
              name: sysinput
              protocol: TCP
            - containerPort: 9600
              name: http
              protocol: TCP
            - containerPort: 5044
              name: tcp
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /usr/share/logstash/config/
            - name: pipeline
              mountPath: /usr/share/logstash/pipeline/
      volumes:
        - name: config
          configMap:
            defaultMode: 429
            name: logstash-config
            items:
              - key: logstash.yml
                path: logstash.yml
        - name: pipeline
          configMap:
            defaultMode: 429
            name: logstash-config
            items:
              - key: logstash.conf
                path: logstash.conf
---
apiVersion: v1
kind: Service
metadata:
  name: logstash
  namespace: elk
spec:
  selector:
    k8s-app: logstash
  ports:
    - port: 8088
      name: heroku
      protocol: TCP
      targetPort: sysinput
    - port: 5044
      name: beats
      protocol: TCP
      targetPort: tcp
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: logstash
  namespace: elk
spec:
  entryPoints:
    - websecure
  routes:
  - match: HostSNI(`*`)
    services:
    - name: logstash
      namespace: elk
      port: 8088
