apiVersion: v1
kind: PersistentVolume
metadata:
  name: logstash
  namespace: elk
  labels:
    type: local
spec:
  storageClassName: logstash-data
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/ubuntu/data/logstash"
  claimRef:
    name: ls-pv-claim
    namespace: elk
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ls-pv-claim
  namespace: elk
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: logstash-data
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: logstash
  name: logstash
  namespace: elk
spec:
  selector:
    matchLabels:
      k8s-app: logstash
  template:
    metadata:
      labels:
        k8s-app: logstash
    spec:
      containers:
        - name: logstash
          image: logstash:8.15.2
          command:
            - bash 
            - -c 
            - |
              bin/logstash-keystore create -f
              echo "${ES_USERNAME}" | bin/logstash-keystore add ES_USER
              echo "${ES_PASSWORD}" | bin/logstash-keystore add ES_PWD
              echo "${LOGSTASH_USERNAME}" | bin/logstash-keystore add LS_USER
              echo "${LOGSTASH_PASSWORD}" | bin/logstash-keystore add LS_PWD
              bin/logstash-plugin install  file:///tmp/logstash-offline-plugins-8.15.2.zip
              bin/logstash
          args:
            #- "--config.reload.automatic"
          env:
            - name: LS_JAVA_OPTS
              value: "-Xmx512m -Xms512m"
            - name: ELASTICSEARCH_HOSTS
              value: http://elasticsearch:9200
            - name: LOGSTASH_KEYSTORE_PASS
              valueFrom:
                secretKeyRef:
                  name: popersecret
                  key: ls-keystore-password
            - name: ELASTICSEARCH_HOSTS
              value: http://elasticsearch:9200
            - name: LOGSTASH_KEYSTORE_PASS
              valueFrom:
                secretKeyRef:
                  name: popersecret
                  key: ls-keystore-password
            - name: ES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: popersecret
                  key: es-username
            - name: ES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: popersecret
                  key: es-password
            - name: LOGSTASH_USERNAME
              valueFrom:
                secretKeyRef:
                  name: popersecret
                  key: logstash-username
            - name: LOGSTASH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: popersecret
                  key: logstash-password
          ports:
            - containerPort: 8088
              name: sysinput
              protocol: TCP
            - containerPort: 9600
              name: http
              protocol: TCP
            - containerPort: 5044
              name: tcp
              protocol: TCP
          resources:
            limits:
              memory: 512Mi
              cpu: 0.5
            requests:
              cpu: 0.1
              memory: 512Mi
          volumeMounts:
            - name: config
              mountPath: /usr/share/logstash/config/logstash.yml
              subPath: logstash.yml
            - name: config
              mountPath: /usr/share/logstash/config/pipelines.yml
              subPath: pipelines.yml
            - name: ls-data
              subPath: logstash-offline-plugins-8.15.2.zip
              readOnly: true
              mountPath: /tmp/logstash-offline-plugins-8.15.2.zip
      volumes:
        - name: ls-data
          persistentVolumeClaim:
            claimName: ls-pv-claim
        - name: config
          configMap:
            defaultMode: 429
            name: logstash-config
            items:
              - key: logstash.yml
                path: logstash.yml
              - key: pipelines.yml
                path: pipelines.yml
       #- name: pipeline
       #  configMap:
       #    defaultMode: 429
       #    name: logstash-config
       #    items:
       #      - key: logstash.conf
       #        path: logstash.conf
---
apiVersion: v1
kind: Service
metadata:
  name: logstash
  namespace: elk
spec:
  selector:
    k8s-app: logstash
  ports:
    - port: 8088
      name: heroku
      protocol: TCP
      targetPort: sysinput
    - port: 5044
      name: beats
      protocol: TCP
      targetPort: tcp
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: logstash
  namespace: elk
spec:
  entryPoints:
    - websecure
  routes:
  - match: HostSNI(`*`)
    services:
    - name: logstash
      namespace: elk
      port: 8088
